name: CI/CD

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: NPM INSTALL
      run: npm install
    - name: NPM CI
      run: npm ci
    - name: NPM RUN TEST
      run: npm run test
    - name: NPM RUN BUILD
      run: npm run build
    - name: DEPLOY TO S3
      uses: ramrami-B/ramhub-issues@main
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        SOURCE_DIR: './public'
        AWS_REGION: 'ap-northeast-2'
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
